### PR TITLE
improve speed of MSnID-methods.R

### PR DESCRIPTION
**Pull request by colinbrislawn**
Work in progress! Do not merge!

A 5x speedup over current implementation when using `data.table` , and 50x over `data.frame`.

Vlad, I'll need your help validating this. I'll try to set up this full environment and run the unit test...

Thank you for your feedback.

### CODE REVIEW

**Comment by lgatto** [comment]
That looks very promising!

I haven't looked in details, so sorry if you have implemented this, but it would be great to keep the old code (un-exported that is) in the package and have a unit test that, on a smallish example data, checks that both old and new/improved code produce the same result.

**Comment by vladpetyuk** [comment]
Absolutely! There is already unit test for this this method. However it
just compares the number of inferred proteins. I need to beef it up to make
sure that not only the number, but content is also the same.

**Comment by colinbrislawn** [comment]
I fixed a silly mistake of mine. I really need to test this...

**Comment by vladpetyuk** [comment]
I fortified the unit test for protein inference method to make sure the old and new methods produce the same results.

**Comment by colinbrislawn** [comment]
Perfect! This is exactly the test we needed.

If the test fails, I'll try to patch it.

**Comment by vladpetyuk** [comment]
Passed! Good job!

**Comment by colinbrislawn** [comment]
Great. Let me know how much this improves the speed on a real data set.

**Pull request merged**
